apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudmart-config
  namespace: cloudmart-prod
data:
  AWS_REGION: ap-south-1
  STORE_BACKEND: dynamodb
  DYNAMODB_TABLE: REPLACE_WITH_DYNAMODB_TABLE_NAME
  DB_BACKEND: postgres
  SECRETS_MANAGER_SECRET_NAME: REPLACE_WITH_RDS_SECRET_NAME
  QUEUE_BACKEND: sqs
  SQS_QUEUE_URL: REPLACE_WITH_SQS_QUEUE_URL
  EMAIL_BACKEND: ses
  FROM_EMAIL: noreply@cloudmart.example
  PRODUCT_SERVICE_URL: http://product-service:8001
  ORDER_SERVICE_URL: http://order-service:8002
