apiVersion: v1
kind: ServiceAccount
metadata:
  name: product-service
  namespace: cloudmart-prod
  annotations:
    eks.amazonaws.com/role-arn: REPLACE_WITH_PRODUCT_SERVICE_IRSA_ROLE_ARN
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: order-service
  namespace: cloudmart-prod
  annotations:
    eks.amazonaws.com/role-arn: REPLACE_WITH_ORDER_SERVICE_IRSA_ROLE_ARN
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: user-service
  namespace: cloudmart-prod
  annotations:
    eks.amazonaws.com/role-arn: REPLACE_WITH_USER_SERVICE_IRSA_ROLE_ARN
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: notification-service
  namespace: cloudmart-prod
  annotations:
    eks.amazonaws.com/role-arn: REPLACE_WITH_NOTIFICATION_SERVICE_IRSA_ROLE_ARN
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend
  namespace: cloudmart-prod
